### PR TITLE
Add privacy policy

### PR DESCRIPTION
**Pull request by siavashs**
Atlassian requires a privacy policy for all applications on Marketplace after 31 January 2019.
I added a simple one, feel free to discuss with legal department in the company and change or update it.

### CODE REVIEW

**Comment by siavashs** [comment]
@flamein  Can you squash the commits?
The releases on Github will now use the commit messages.

**Comment by flamein** [comment]
Hmmm, shit, i thought I used a squash commit :(

**Comment by siavashs** [comment]
No problem, we can edit the release after it is created.

**Comment by flamein** [comment]
I've disabled merge commit (and rebase merge) as an option

**Pull request merged**
